### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by NadaBen** [damonjones/InsigAWSBundle#1]
Hello,
I want to use your bundle, 
i tried "damonjones/insig-aws-bundle":"*" in my composer,
but this error is shown
 The requested package damonjones/insig-aws-bundle could not be found in any version, there may be a typo in the package name

**Comment by damonjones** [comment]
You should be able to install dev-master:
`composer require damonjones/insig-aws-bundle dev-master`

I'm not sure whether the Amazon product API still works (I haven't used this bundle for a few years). I'd recommend looking for a newer/more frequently maintained package.
